#!/usr/bin/env python

import sys
sys.path.insert(0, "/srv/hacksense/lib")

import hacksense
import logging
import time

hacksense.setup_logging(redirect=True)

ttl = 5

current_dali_preset = 0

def callback(ch, method, properties, body):
    global conn
    global current_dali_preset

    topic = method.routing_key
    timestamp = properties.timestamp
    headers = properties.headers

    logging.info("%s %s %r" % (timestamp, topic, headers))

    if time.time()-timestamp > 10:
        logging.warning("Ignoring delayed button message")
        return

    if topic == 'doorbot.buttons.red.shortpress':
        conn.publish('actions.play_sound', {"filename": "red_button/", "ttl": ttl})
        #conn.publish('doorbot.lcd.display', {'line1': 'Long-press to', 'line2': 'change status', 'flash': 2})
    elif topic == 'doorbot.buttons.green.shortpress':
        current_dali_preset += 1
        conn.publish('dali.preset', {'preset': current_dali_preset}, '')
    else:
        return

conn = hacksense.AMQPTopic()
conn.subscribe_callback("doorbot.buttons.#", callback)
