#!/usr/bin/env python

import sys
sys.path.insert(0, "/srv/hacksense/lib")

import hacksense
import logging
import time

hacksense.setup_logging(redirect=True)

ttl = 5

def callback(ch, method, properties, body):
    global conn

    topic = method.routing_key
    timestamp = properties.timestamp
    headers = properties.headers

    logging.info("%s %s %r" % (timestamp, topic, headers))

    if time.time()-timestamp > 10:
        logging.warning("Ignoring delayed button message")
        return

    if topic == 'doorbot.buttons.red.shortpress':
        conn.publish('actions.play_sound', {"filename": "bingo.mp3", "ttl": ttl})
        conn.publish('doorbot.lcd.display', {'line1': 'Bingo!', 'line2': '', 'flash': 2})
        conn.publish('doorbot.lcd.display', {'line1': 'Long-press to', 'line2': 'change status', 'flash': 2})
    elif topic == 'doorbot.buttons.green.shortpress':
        conn.publish('actions.speak', {'data': 'tomato',
                                       'espeak_voice': 'en-us',
                                       'ttl': ttl})
        conn.publish('doorbot.lcd.display', {'line1': 'Long-press to', 'line2': 'change status', 'flash': 2})
    else:
        return

conn = hacksense.AMQPTopic()
conn.subscribe_callback("doorbot.buttons.#", callback)
