#!/usr/bin/env python

import sys
sys.path.insert(0, "/srv/hacksense/lib")

import hacksense
import logging
import time
import urllib
import urllib2

open_secret = hacksense.config.get("open_secret", "")
closed_secret = hacksense.config.get("closed_secret", "")
status_timeout = 7200

global stored_status
stored_status = (0, 'closed')

def push_status_to_server(status):
    if status == 'open':
        values = {'k': open_secret}
        data = urllib.urlencode(values)
        req = urllib2.Request('http://www.edinburghhacklab.com/internal/occupancy.php', data)
        if urllib2.urlopen(req).read() == 'DONE':
            return True
        else:
            return False
    elif status == 'closed':
        values = {'k': closed_secret}
        data = urllib.urlencode(values)
        req = urllib2.Request('http://www.edinburghhacklab.com/internal/occupancy.php', data)
        if urllib2.urlopen(req).read() == 'DONE':
            return True
        else:
            return False

def lcd(line1, line2=""):
    conn.publish("doorbot.lcd.display", {"line1": line1, "line2": line2})

def say(text):
    conn.publish("actions.speak", {"data": text})

def callback(ch, method, properties, body):
    global stored_status

    topic = method.routing_key
    timestamp = properties.timestamp
    headers = properties.headers

    if time.time()-timestamp > 10:
        logging.warning("Ignoring delayed button message")
        return

    #current_status_timestamp, current_status = rr.get('hacksense:labstatus')
    current_status_timestamp, current_status = stored_status
    current_status_age = time.time()-current_status_timestamp

    if topic in ['doorbot.buttons.green.shortpress', 'doorbot.buttons.green.longpress']:
        new_status = 'open'
    elif topic in ['doorbot.buttons.red.shortpress', 'doorbot.buttons.red.longpress']:
        new_status = 'closed'
    else:
        return

    if topic in ['doorbot.buttons.green.longpress', 'doorbot.buttons.red.longpress']:
        press = 'long'
    else:
        press = 'short'

    if new_status == current_status and current_status_age < status_timeout and press == 'short':
        say("The status is already %s" % (new_status))
        return
        
    if new_status == 'open':
        #rr.put('hacksense:labstatus', (time.time(), 'open'))
        stored_status = (time.time(), 'open')
        lcd("Opening...")
        if push_status_to_server('open'):
            lcd("Status: Open")
            say("Status set to open")
        else:
            lcd("Status: Open", "Tweet failed")
            say("Sorry, I couldn't reach twitter")

    elif new_status == 'closed':
        #rr.put('hacksense:labstatus', (time.time(), 'closed'))
        stored_status = (time.time(), 'closed')
        lcd("Closing...")
        if push_status_to_server('closed'):
            lcd("Status: Closed")
            say("Status set to closed")
        else:
            lcd("Status: Closed", "Tweet failed")
            say("Sorry, I couldn't reach twitter")

conn = hacksense.AMQPTopic()
conn.subscribe_callback("doorbot.buttons.#", callback)
