#!/usr/bin/env python

import sys
sys.path.insert(0, "/srv/hacksense/lib")

import hacksense
import logging
import smartcard
import time

from smartcard.CardRequest import CardRequest
from smartcard.util import toHexString, toASCIIString, PACK

hacksense.setup_logging(redirect=True)
logging.getLogger().setLevel(logging.DEBUG)
conn = hacksense.AMQPTopic()

while True:
    try:
        cardrequest = CardRequest(newcardonly=True, timeout=1)
        cardservice = cardrequest.waitforcard()

        connection = cardservice.connection
        connection.connect()

        atr = toHexString(connection.getATR(), PACK)

        data, sw1, sw2 = connection.transmit([0xFF, 0xCA, 0x00, 0x00, 0x00])
        uid = toHexString(data, PACK)

        logging.info("%s %s %s" % (time.ctime(), atr, uid))
        conn.publish("doorbot.card.swipe", {"atr": atr, "uid": uid})
        conn.publish("doorbot.lcd.display", {"flash": 1, "line1": "UID:", "line2": uid})

        #time.sleep(1)

    except smartcard.Exceptions.CardRequestTimeoutException:
        pass
